name: Build Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: v14.2.0
    - run: npm install
    - run: npm run build
    - name: Cache
      uses: actions/cache@v2.0.0
      with:
        path: node_modules
        key: ${{ runner.os }}-primes
    - name: Deploy
      uses: s0/git-publish-subdir-action@master
      env:
        REPO: progressive-player@github.com:progressive-player/progressive-player.github.io.git
        BRANCH: master
        FOLDER: dist
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
