name: Build Page

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: v14.2.0
    - run: npm install
    - run: npm run build
    - name: Cache
      uses: actions/cache@v2.0.0
      with:
        path: node_modules
        key: ${{ runner.os }}-primes
    - name: checkout
      uses: actions/checkout@master
      with:
        ref: master
    - name: push
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'publish'
        force-add: 'true'
        files: dist/**/*
        name: DamenH
        email: damen@damenhannah.com
